# Change these first
owner: Snaky4life # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: ModMail 1
    url: $BOT1
    expectedStatusCodes:
      - 200
  - name: ModMail 2
    url: $BOT2
    expectedStatusCodes:
      - 200
  - name: ModMail 3
    url: $BOT3
    expectedStatusCodes:
      - 200
  - name: ModMail 4
    url: $BOT4
    expectedStatusCodes:
      - 200
  - name: ModMail 5
    url: $BOT5
    expectedStatusCodes:
      - 200

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status
  logoUrl: https://snaky4life.github.io/ModMail-status/
  name: ModMail
  introTitle: "**Welcome!**"
  introMessage: Here, you may see the status of the std5 ModMail bot.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
